name: Build Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.0

      - name: Installing Dependencies
        run: |
          sudo apt-get install libopenal-dev
          haxelib --quiet git hxopenal https://github.com/Leather128/hxopenal.git
          haxelib --quiet install format

      - name: Building Demo 1
        run: |
          cd demo/basic-audio-playback
          haxe build.hxml
          cd ../../

      - name: Building Demo 2
        run: |
          cd demo/audio-position-shifting
          haxe build.hxml
          cd ../../

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.0

      - name: Installing Dependencies
        run: |
          haxelib --quiet git hxopenal https://github.com/Leather128/hxopenal.git
          haxelib --quiet install format

      - name: Building Demo 1
        run: |
          cd demo/basic-audio-playback
          haxe build.hxml
          cd ../../

      - name: Building Demo 2
        run: |
          cd demo/audio-position-shifting
          haxe build.hxml
          cd ../../

  MacOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.0

      - name: Installing Dependencies
        run: |
          haxelib --quiet git hxopenal https://github.com/Leather128/hxopenal.git
          haxelib --quiet install format

      - name: Building Demo 1
        run: |
          cd demo/basic-audio-playback
          haxe build.hxml
          cd ../../

      - name: Building Demo 2
        run: |
          cd demo/audio-position-shifting
          haxe build.hxml
          cd ../../
