name: Build Tests

on:
	push:
	branches: [main]
	workflow_dispatch:

jobs:
	Linux (Ubuntu):
		runs-on: ubuntu-latest
		steps:
		- name: Checkout
			uses: actions/checkout@main
			with:
				submodules: true

		- name: Setup Haxe
			uses: krdlab/setup-haxe@master
			with:
				haxe-version: 4.3.0

		- name: Installing Dependencies
			run: sudo apt-get install libopenal-dev

		- name: Building
			run: |
				haxelib --quiet git hxopenal https://github.com/Leather128/hxopenal.git
				haxelib --quiet install format
				cd demo/sound-abstraction
				haxe build.hxml
	
	Windows:
		runs-on: windows-latest
		steps:
		- name: Checkout
			uses: actions/checkout@main
			with:
				submodules: true

		- name: Setup Haxe
			uses: krdlab/setup-haxe@master
			with:
				haxe-version: 4.3.0

		- name: Building
			run: |
				haxelib --quiet git hxopenal https://github.com/Leather128/hxopenal.git
				haxelib --quiet install format
				cd demo/sound-abstraction
				haxe build.hxml
	
	MacOS:
		runs-on: macos-latest
		steps:
		- name: Checkout
			uses: actions/checkout@main
			with:
				submodules: true

		- name: Setup Haxe
			uses: krdlab/setup-haxe@master
			with:
				haxe-version: 4.3.0

		- name: Building
			run: |
				haxelib --quiet git hxopenal https://github.com/Leather128/hxopenal.git
				haxelib --quiet install format
				cd demo/sound-abstraction
				haxe build.hxml
