name: Testing
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.0

      - name: Installing Dependencies
        run: sudo apt-get install libopenal-dev

      - name: Compiling 
        run: |
          haxelib --quiet git hxopenal https://github.com/Leather128/hxopenal.git
          haxelib --quiet install format
          cd demo/sound-abstraction
          haxe build.hxml
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test-linux
          path: demo/sound-abstraction/bin
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.0

      - name: Compiling 
        run: |
          haxelib --quiet git hxopenal https://github.com/Leather128/hxopenal.git
          haxelib --quiet install format
          cd demo/sound-abstraction
          haxe build.hxml
  Mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.0

      - name: Compiling 
        run: |
          haxelib --quiet git hxopenal https://github.com/Leather128/hxopenal.git
          haxelib --quiet install format
          cd demo/sound-abstraction
          haxe build.hxml
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test-mac
          path: demo/sound-abstraction/bin
